<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-04-26T17:09:31+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/London',
];
