<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2019-04-29T14:24:08+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      seo.url_rewriting
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'en_GB',
    'version_installed' => '8.5.1',
    'version_db_installed' => '20190301133300',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1556294969,
        'latest_version' => '8.5.1',
        'do_page_reindex_check' => false,
    ],
    'session' => [
        'handler' => 'database',
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
];
